kind: Pod
apiVersion: v1
metadata:
  name: ubuntu-compute-SF
spec:
  nodeSelector:
    "kubernetes.io/hostname": compute-contrail-SF
  containers:
    - name: ubuntu-compute-SF
      image: ubuntu
  restartPolicy: Never
