kind: Pod
apiVersion: v1
metadata:
  name: ubuntu-compute-ny
spec:
  nodeSelector:
    "kubernetes.io/hostname": compute-contrail-ny
  containers:
    - name: ubuntu-compute-ny
      image: virtualhops/ato-ubuntu:latest
  restartPolicy: Never
